language: php
php:
  - 7.2
before_script:
  - composer self-update
  - composer install
  - phpenv rehash
script: vendor/bin/phpspec run -n
notifications:
  email:
    - tworzenieweb@gmail.com
sudo: false
